"use client";
import { useState } from "react";
import { Check, Copy, Trophy } from "lucide-react";
export type RankEntry={id:string;name:string;count:number;earnings:number;rank:number};
export default function Leaderboard({monthly,allTime,month}:{monthly:RankEntry[];allTime:RankEntry[];month:string}){
 const [period,setPeriod]=useState<"monthly"|"allTime">("monthly");const [copied,setCopied]=useState(false);const entries=period==="monthly"?monthly:allTime;const label=period==="monthly"?month+" 月榜":"总榜";
 const copyTopTen=async()=>{const lines=[`🏆 棉花俱乐部陪陪单量排行榜｜${label}`,"",...entries.slice(0,10).map((p,index)=>`${index+1}. ${p.name}｜${p.count} 单量｜RM ${p.earnings.toFixed(2)}`),"", "统计方式：半小时 = 1 单量，1 小时 = 2 单量；不计算礼物单。"];try{await navigator.clipboard.writeText(lines.join("\n"));setCopied(true);setTimeout(()=>setCopied(false),2200)}catch{window.prompt("复制以下聊天记录",lines.join("\n"))}};
 return <section className="orders-panel leaderboard"><div className="panel-title"><h2><Trophy size={19}/> 陪陪单量排行榜</h2><div className="rank-actions"><div className="rank-switch"><button className={period==="monthly"?"selected":""} onClick={()=>setPeriod("monthly")}>每月</button><button className={period==="allTime"?"selected":""} onClick={()=>setPeriod("allTime")}>总量</button></div><button className="secondary rank-copy" onClick={copyTopTen}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?"已复制":"复制前10聊天记录"}</button></div></div><p className="rank-caption">{label} · 按服务时长单量排名，同单量按收入排序</p><div className="rank-grid">{entries.slice(0,10).map(p=><div className="rank-person" key={p.id}><span className={"rank-number podium-"+p.rank}>{String(p.rank).padStart(2,"0")}</span><strong>{p.name}</strong><div><b>{p.count} <small>单量</small></b><span>RM {p.earnings.toFixed(2)}</span></div></div>)}</div>{!entries.length&&<p className="rank-empty">{period==="monthly"?"这个月还没有服务订单":"还没有服务订单记录"}</p>}<p className="rank-caption">显示前10名 · 半小时 = 1 单量、1 小时 = 2 单量；收入为陪陪工资，不计算礼物单。</p></section>;
}
