"use client";

import { useEffect, useMemo, useState } from "react";
import { Banknote, Check, ChevronDown, ChevronUp, CircleAlert, CreditCard, Eye, LoaderCircle } from "lucide-react";
import Workspace from "../components/Workspace";
import Modal from "../components/Modal";

type PendingOrder = { id: string; orderNo: string; date: string; service: string; type: string; wage: number; status: string };
type PaymentItem = { companionId: string; name: string; paymentMethod: string; paymentContent: string; paymentImage: string; missingPaymentInfo: boolean; orderCount: number; totalWage: number; orders: PendingOrder[] };
type History = { _id: string; companionName: string; orderCount: number; totalWage: number; paidAt: string; notes: string };
type PaymentData = { period: { label: string }; summary: { companionCount: number; orderCount: number; totalWage: number }; items: PaymentItem[]; history: History[] };
const current = () => { const now = new Date(); const month = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kuala_Lumpur", year: "numeric", month: "2-digit" }).format(now); const day = Number(new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Kuala_Lumpur", day: "2-digit" }).format(now)); return { month, half: day <= 15 ? "1" : "2" }; };
const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kuala_Lumpur", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
const rm = (value: number) => `RM ${value.toFixed(2)}`;

export default function CompanionPaymentsPage() {
  const initial = current(); const [month, setMonth] = useState(initial.month); const [half, setHalf] = useState(initial.half); const [data, setData] = useState<PaymentData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [selected, setSelected] = useState<Set<string>>(new Set()); const [expanded, setExpanded] = useState<Set<string>>(new Set()); const [confirming, setConfirming] = useState(false); const [paying, setPaying] = useState(false); const [paidAt, setPaidAt] = useState(today); const [notes, setNotes] = useState(""); const [toast, setToast] = useState("");
  const load = () => { setLoading(true); setError(""); fetch(`/api/companion-payments?month=${month}&half=${half}`).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); setSelected(new Set()); }).catch(error => setError(error instanceof Error ? error.message : "加载失败")).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, [month, half]);
  const selectedItems = useMemo(() => data?.items.filter(item => selected.has(item.companionId)) || [], [data, selected]);
  const selectedWage = selectedItems.reduce((sum, item) => sum + item.totalWage, 0); const allSelected = Boolean(data?.items.length) && data!.items.every(item => selected.has(item.companionId));
  const toggle = (id: string) => setSelected(current => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; });
  const confirm = async () => { setPaying(true); try { const response = await fetch("/api/companion-payments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ companionIds: [...selected], month, half, paidAt, notes }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setConfirming(false); setToast(`已确认 ${body.paid.length} 位陪陪，合计 ${rm(body.totalWage)}`); setNotes(""); load(); } catch (error) { setToast(error instanceof Error ? error.message : "付款确认失败"); } finally { setPaying(false); } };
  return <Workspace section="companionPayments"><div className="content payment-page"><div className="heading"><div><div className="eyebrow">COMPANION PAYOUTS</div><h1>陪陪付款</h1><p>按半月结算待发放订单，确认后自动标记为已付款。</p></div></div>
    <section className="payout-hero"><span><Banknote size={27}/></span><div><strong>{data?.period.label || "正在读取结算期"}</strong><p>只显示状态为「可发放」的订单。</p></div><div className="payout-metrics"><div><b>{loading ? "—" : data?.summary.companionCount || 0}</b><small>待付陪陪</small></div><div><b>{loading ? "—" : data?.summary.orderCount || 0}</b><small>待付订单</small></div><div><b>{loading ? "—" : rm(data?.summary.totalWage || 0)}</b><small>待付总工资</small></div></div></section>
    <section className="orders-panel payout-panel"><div className="payout-toolbar"><label>结算月份<input type="month" value={month} onChange={event => setMonth(event.target.value)} /></label><label>结算期<select value={half} onChange={event => setHalf(event.target.value)}><option value="1">上半月（1–15日）</option><option value="2">下半月（16日–月末）</option></select></label>{selected.size > 0 && <button className="primary" onClick={() => setConfirming(true)}><CreditCard size={17}/>确认付款 {selected.size} 位 · {rm(selectedWage)}</button>}</div>
      {loading ? <div className="payout-loading"><LoaderCircle size={25}/><strong>正在整理待付款资料…</strong></div> : error ? <div className="empty error"><h3>无法加载付款资料</h3><p>{error}</p><button className="secondary" onClick={load}>重试</button></div> : <div className="table-wrap payout-table"><table><thead><tr><th><input aria-label="选择所有陪陪" type="checkbox" checked={allSelected} onChange={() => setSelected(allSelected ? new Set() : new Set(data!.items.map(item => item.companionId)))} /></th><th>陪陪</th><th>待付单量</th><th>应发工资</th><th>付款资料</th><th>订单</th></tr></thead><tbody>{data?.items.map(item => <><tr key={item.companionId}><td><input aria-label={`选择 ${item.name}`} type="checkbox" checked={selected.has(item.companionId)} onChange={() => toggle(item.companionId)} /></td><td><div className="person"><span className="person-icon P">{item.name.slice(0, 1)}</span><b>{item.name}</b></div></td><td><strong>{item.orderCount} <small>单</small></strong></td><td><strong className="payout-wage">{rm(item.totalWage)}</strong></td><td>{item.missingPaymentInfo ? <span className="payout-missing"><CircleAlert size={14}/>缺付款资料</span> : <button className="payout-payment" onClick={() => setExpanded(current => new Set(current).add(item.companionId))}>{item.paymentMethod} · 查看</button>}</td><td><button className="secondary payout-expand" onClick={() => setExpanded(current => { const next = new Set(current); next.has(item.companionId) ? next.delete(item.companionId) : next.add(item.companionId); return next; })}>{expanded.has(item.companionId) ? <ChevronUp size={16}/> : <ChevronDown size={16}/>} {expanded.has(item.companionId) ? "收起" : "查看订单"}</button></td></tr>{expanded.has(item.companionId) && <tr key={`${item.companionId}-details`} className="payout-detail-row"><td colSpan={6}><div className="payout-details"><div className="payout-payment-card"><b>付款资料</b><span>{item.paymentMethod || "未填写付款方式"}</span><p>{item.paymentContent || "未填写付款内容"}</p>{item.paymentImage && <img src={item.paymentImage} alt={`${item.name} 的付款资料`} />}</div><div><b>本期可发放订单</b>{item.orders.map(order => <div className="payout-order" key={order.id}><span>{order.orderNo} · {order.date} · {order.service}</span><strong>{rm(order.wage)}</strong></div>)}</div></div></td></tr>}</>)}</tbody></table>{!data?.items.length && <div className="empty"><Check size={30}/><h3>这个结算期没有待付款订单</h3><p>所有可发放订单都已处理，或尚未有订单。</p></div>}</div>}</section>
    <section className="orders-panel payout-history"><div className="panel-title"><h2>本期付款记录</h2><span>{data?.history.length || 0} 笔</span></div>{data?.history.length ? <div className="table-wrap"><table><thead><tr><th>陪陪</th><th>订单</th><th>实付工资</th><th>付款日期</th><th>备注</th></tr></thead><tbody>{data.history.map(record => <tr key={record._id}><td>{record.companionName}</td><td>{record.orderCount} 单</td><td>{rm(record.totalWage)}</td><td>{record.paidAt}</td><td>{record.notes || <span className="muted">—</span>}</td></tr>)}</tbody></table></div> : <p className="payout-history-empty">这个结算期还没有付款记录。</p>}</section>
  </div>{confirming && <Modal title="确认陪陪付款" onClose={() => !paying && setConfirming(false)}><div className="form-body payout-confirm"><div className="payout-confirm-total"><span>本次将付款给</span><strong>{selectedItems.length} 位陪陪 · {rm(selectedWage)}</strong><small>对应的可发放订单会改为「已付款」。</small></div><label>实际付款日期<input type="date" value={paidAt} onChange={event => setPaidAt(event.target.value)} /></label><label>付款备注（选填）<textarea rows={3} value={notes} placeholder="例如：已完成 TNG 转账" onChange={event => setNotes(event.target.value)} /></label></div><div className="dialog-actions"><button className="secondary" disabled={paying} onClick={() => setConfirming(false)}>取消</button><button className="primary" disabled={paying} onClick={confirm}>{paying ? "确认中…" : "确认并标记已付款"}</button></div></Modal>}{toast && <div className="toast"><Check size={17}/>{toast}</div>}</Workspace>;
}
