"use client";
import { useEffect, useState } from "react";
import { Check, Headphones, Pencil, Plus, Search, Trash2, UserRound } from "lucide-react";
import Workspace from "../components/Workspace";
import Modal from "../components/Modal";
import type { CustomerService } from "@/lib/customer-service-domain";
export default function CustomerServicesPage() {
  const [items,setItems]=useState<CustomerService[]>([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[revision,setRevision]=useState(0),[editor,setEditor]=useState<CustomerService|"new"|null>(null),[deleting,setDeleting]=useState<CustomerService|null>(null),[toast,setToast]=useState("");
  useEffect(()=>{const c=new AbortController();setLoading(true);fetch("/api/customer-services?q="+encodeURIComponent(q),{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.items)}).catch(e=>!c.signal.aborted&&setError(e.message)).finally(()=>!c.signal.aborted&&setLoading(false));return()=>c.abort()},[q,revision]);
  const saved=(message:string)=>{setEditor(null);setRevision(n=>n+1);setToast(message);setTimeout(()=>setToast(""),3500)};
  const totalOrders=items.reduce((sum,item)=>sum+(item.orderCount||0),0);
  return <Workspace section="customerServices"><div className="content customer-page"><div className="heading"><div><div className="eyebrow">CUSTOMER SERVICE MANAGEMENT</div><h1>客服管理</h1><p>建立客服资料，清楚掌握每位客服对接成功的订单。</p></div><button className="primary" onClick={()=>setEditor("new")}><Plus size={18}/>新增客服</button></div>
    <section className="customer-hero"><span className="customer-hero-icon"><UserRound size={26}/></span><div><strong>客服工作台</strong><p>新订单可直接选择客服，历史对接单会自动累计。</p></div><div className="customer-metrics"><div><strong>{loading?"—":items.length}</strong><span>位客服</span></div><div><strong>{loading?"—":totalOrders}</strong><span>对接成功单</span></div></div></section>
    <section className="orders-panel customer-panel"><div className="filter-row"><label className="search"><Search size={18}/><input aria-label="搜索客服" placeholder="输入客服名称搜寻" value={q} onChange={e=>setQ(e.target.value)}/></label></div>{error?<div className="empty error">{error}</div>:<div className="table-wrap"><table><thead><tr><th>客服名称</th><th>对接成功单子</th><th>备注</th><th>操作</th></tr></thead><tbody>{items.map(item=><tr key={item._id}><td><div className="person"><span className="person-icon P">{item.name.slice(0,1)}</span><b>{item.name}</b></div></td><td><span className="customer-order-count">{item.orderCount||0} <small>单</small></span></td><td className="roster-note">{item.notes||<span className="muted">暂无备注</span>}</td><td><div className="row-actions"><button className="secondary" onClick={()=>setEditor(item)}><Pencil size={14}/>编辑</button><button className="icon-btn delete" onClick={()=>setDeleting(item)}><Trash2 size={17}/></button></div></td></tr>)}</tbody></table>{!loading&&!items.length&&<div className="empty"><h3>还没有客服</h3><p>点击“新增客服”建立第一份资料。</p></div>}</div>}</section>
  </div>{editor&&<CustomerEditor item={editor} onClose={()=>setEditor(null)} onSaved={saved}/>} {deleting&&<Modal title="删除客服" onClose={()=>setDeleting(null)}><div className="confirm"><p>确定删除 <strong>{deleting.name}</strong>？</p><p className="muted">历史订单会保留客服名称。</p><div className="dialog-actions"><button className="secondary" onClick={()=>setDeleting(null)}>取消</button><button className="danger" onClick={async()=>{const r=await fetch("/api/customer-services/"+deleting._id,{method:"DELETE"});if(r.ok){setDeleting(null);saved("客服已删除")}else setToast("删除失败")}}>确认删除</button></div></div></Modal>}{toast&&<div className="toast"><Check size={17}/>{toast}</div>}</Workspace>
}
function CustomerEditor({item,onClose,onSaved}:{item:CustomerService|"new";onClose:()=>void;onSaved:(m:string)=>void}) {
 const [name,setName]=useState(item==="new"?"":item.name),[notes,setNotes]=useState(item==="new"?"":item.notes||""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 return <Modal title={item==="new"?"新增客服":"编辑客服"} onClose={()=>!busy&&onClose()}><form className="customer-editor" onSubmit={async e=>{e.preventDefault();setBusy(true);const r=await fetch("/api/customer-services"+(item==="new"?"":"/"+item._id),{method:item==="new"?"POST":"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,notes})});const d=await r.json();setBusy(false);if(!r.ok)return setError(d.error);onSaved(item==="new"?"客服已新增":"客服已更新")}}><div className="form-body customer-editor-body"><div className="customer-editor-intro"><span><Headphones size={19}/></span><div><strong>{item==="new"?"建立客服资料":"更新客服资料"}</strong><p>客服会用于新订单选择，并自动累计对接成功单。</p></div></div><label className="customer-field"><span>客服名称 <b>必填</b></span><input required autoFocus placeholder="例如：宁宁" value={name} onChange={e=>setName(e.target.value)}/></label><label className="customer-field"><span>备注 <em>选填</em></span><textarea rows={5} placeholder="例如：负责的时段、对接说明" value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<div className="form-error">{error}</div>}</div><div className="dialog-actions customer-editor-actions"><span>保存后可在新增订单内选择这位客服。</span><button type="button" className="secondary" onClick={onClose}>取消</button><button className="primary" disabled={busy}>{busy?"保存中…":"保存客服"}</button></div></form></Modal>
}
